tick_rate = 250

[node]
provider = "bitcoin_core"

[bitcoin_core]
host = "127.0.0.1"
rpc_port = 18443
rpc_user = "polaruser"
rpc_password = "polarpass"
zmq_port = 28334

[core_lightning]
rest_address = "http://127.0.0.1:3010"
rest_rune = "replaceme"

[lnd]
rest_address = "https://127.0.0.1:8080"
macaroon_hex = "replaceme>

[price]
enabled = true
currency = "USD"

[fees]
enabled = true
