tick_rate = 250
streamer_mode = false
node_switch_interval = 5

[[nodes]]
name = "Bitcoin Core"
provider = "bitcoin_core"

[nodes.bitcoin_core]
host = "127.0.0.1"
rpc_port = 18443
rpc_user = "polaruser"
rpc_password = "polarpass"
zmq_port = 28334

[price]
enabled = true
currency = "USD"
big_text = true
variation = "minute"
variation_threshold = 0.0

[fees]
enabled = true

[touch]
enabled = true
swap_xy = false
invert_x = false
invert_y = false
